# Generated by Django 5.2.8 on 2025-11-14 02:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="content",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
